site_name: My Docs
theme:
  name: material
  features:
    - content.code.copy
    - search.highlight
    - navigation.top
    # - navigation.tabs


plugins:
  - search:
      lang: zh

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
