site_name: My Docs
theme:
  name: material
  # custom_dir: overrides
  features:
    # 复制到剪贴板按钮
    - content.code.copy
    # 代码注释
    - content.code.annotate
    # 启用搜索突出显示功能
    - search.highlight
    # navigation.top
    - navigation.top
    # 顶级部分将呈现在上方视口标题下方的菜单层中
    - navigation.tabs
    # 启用粘滞选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    - navigation.tabs.sticky
    # 启用部分后，顶级部分将在侧边栏中呈现为上方视口的组
    - navigation.sections
    # - navigation.expand



plugins:
  - search:
      lang: en

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 

extra_css:
  - stylesheets/extra.css

